spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
        metadata:
          application: ${spring.application.name}
        tags: urlprefix-${server.servlet.context-path}
