spring:
  application.name: player-events
  rabbitmq:
    addresses: ${sm://lostcities_event_queue_url}
    port: 1883
  cloud:
    consul.enabled: false

server:
  port: 8093
  forward-headers-strategy: framework
  servlet:
      context-path: /api/player-events

management:
    endpoints:
        web.exposure.include: metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}

logging:
  level:
    ROOT: error
    io.dereknelson.lostcities: debug
    org.springframework.security.web.FilterChainProxy: error
    org.springframework.amqp.rabbit: error
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: '%d{"yyyy-MM-dd''T''HH:mm:ss,SSS"} application=${spring.application.name} profiles=${spring.profiles.active} %-5level [%thread] %logger : %msg%n'
    dateformat: yyyy-MM-dd'T'HH:mm:ssxxx
  file:
    name: /root/Logs/${spring.application.name}-stage.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
