logging:
  level:
    ROOT: error
    io.dereknelson.lostcities: debug
    org.springframework.security.web.FilterChainProxy: error
    org.springframework.amqp.rabbit: error

spring:
  application.name: player-events
  profiles:
    active: dev



server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
      contextPath: /api

management:
  otlp:
    metrics:
      export:
        url: http://192.168.1.231:4318/v1/metrics
        step: 5s
  endpoint.health:
    show-details: "ALWAYS"
  metrics.tags:
    application: ${spring.application.name}
    host: ${spring.application.name}.lostcities.dev
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 4452
    base-path: /management/${spring.application.name}
