logging:
  level:
    ROOT: error
    io.dereknelson.lostcities: debug
    org.springframework.security.web.FilterChainProxy: error
    org.springframework.amqp.rabbit: error

spring:
  application.name: player-events
  profiles:
    active: dev


server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
      context-path: /api/player-events

management:
    endpoints:
        web.exposure.include: metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}
