logging:
  level:
    ROOT: error
    io.dereknelson.lostcities: debug
    org.springframework.security.web.FilterChainProxy: debug
    org.hibernate: info
    org.springframework.amqp.rabbit.connection: debug

spring:
  profiles:
    active: dev

  rabbitmq:
    host: 172.20.0.60
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
  forward-headers-strategy: framework