logging:
  level:
    ROOT: error
    io.dereknelson.lostcities: debug
    org.springframework.security.web.FilterChainProxy: error
    org.springframework.amqp.rabbit: error

spring:
  application.name: player-events
  rabbitmq:
    host: 172.20.0.60
    port: 5672
    username: guest
    password: guest

server:
  port: 8093
