name: Building application

on: [push]

env:
  GH_USER: ${{ secrets.GH_USER }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NVD_KEY: ${{ secrets.NVD_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Assemble
        run: ./gradlew assemble
      - name: Run Ktlint
        run: ./gradlew ktlintCheck
      - name: Test
        run: ./gradlew check
      - name: Dependency  Scan Cache
        id: dependency-scan-cache
        uses: actions/cache@v4
        with:
          path: owasap
          key: dependency-scan-cache
      - name: Check Dependencies
        run: ./gradlew dependencyCheckAnalyze -Dorg.gradle.jvmargs="-Xmx4g"
      - uses: actions/upload-artifact@v4
        with:
          name: dependency-scan-results
          path: ./build/reports/**
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "./build/test-results/**/*.xml"
      - name: Generate Documentation
        run: ./gradlew dokkaHtml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: build/dokka/html
          TARGET_FOLDER: javadoc
      - name: Semver
        run: ./gradlew semver --patch
      - name: Build docker
        run: ./gradlew jib

