name: Building application

on: [push]

env:
  GH_ACTOR: ${{ secrets.GH_ACTOR }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "7.4"
      - name: Run Ktlint
        run: ./gradlew ktlintCheck
      - name: Assemble
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew check
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "test-results/**/*.xml"
      - name: Build docker
        run: ./gradlew jib
      - name: Generate Documentation
        run: ./gradlew dokkaHtml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: build/dokka/html
          TARGET_FOLDER: javadoc


